name: cicd

on:
  push:
    branches:
  #    - main
      - dev
  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0     

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9.4.0

      - name: Installing dependencies
        run: pnpm i --frozen-lockfile

      - name: Run tests
        run: pnpm run test

      - name: Run extract Addon
        run: pnpm run update

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: List all changed files
        run: |
          echo "## ${{ steps.versioning.outputs.version }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "### Files added: ${{steps.changed-files.outputs.added_files_count}}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          for file in ${{ steps.changed-files.outputs.added_files }}; do 
            echo "$file was added" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          done
          echo "### Files changed: ${{steps.changed-files.outputs.all_changed_and_modified_files_count}}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do 
            echo "$file was changed" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          done
          echo "" >> CHANGELOG.md
      
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: estebanmathia
          author_email: esteban.mathia@supinfo.com
          force: false
          signoff: false
          message: 'add info extract from addon'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}