name: Verify tests and cancel merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-and-cancel-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    #- name: Checkout le code
    #  uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19

    - name: Installing dependencies
      run: npm install

    - name: Run tests
      run: npm run test
      continue-on-error: true