name: Generate SBOM

on:
  push:
    branches:
      - dev-adrien-rules
  pull_request:
    branches:
      - dev-adrien-rules
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
        
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./package-lock.json #Kexa-generate-sbom.spdx.json
          
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: /tmp/sbom-action-zSrk8Q/Kexa-generate-sbom.spdx.json
        
      - name: Commit artifact to main branch
        run: |
          cp Kexa-generate-sbom.spdx.json .
          git add .
          git commit -m "Add artifact to main branch"
          git push origin dev-adrien-rules
