name: Generate SBOM

on:
  push:
    branches:
      - dev-adrien-rules
  pull_request:
    branches:
      - dev-adrien-rules

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >>~/.profile
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >>~/.bashrc
          source ~/.bashrc

      - name: Install Syft
        run: |
          brew install syft

      - name: Generate SBOM
        run: |
          syft . -o syft-text

      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
