name: Generate SBOM

on:
  push:
    branches:
      - dev-adrien-rules
  pull_request:
    branches:
      - dev-adrien-rules

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./Kexa/
