name: Generate SBOM

on:
  push:
    branches:
      - dev-adrien-rules
  pull_request:
    branches:
      - dev-adrien-rules
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
        
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./Kexa/
